spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.private.key=${PRIVATE_PEM}
jwt.public.key=${PUBLIC_PEM}

logging.level.org.springframework.security=DEBUG

google.client.id=540942343774-6ov02iakkgkm4rbjf8tec0igqs1u0scv.apps.googleusercontent.com
